### ISSUE TITLE
Upgrading to latest collector components

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/opentelemetry-collector-configs#122]
We have some pending dependabot updates to update the timespansprocessor to the latest versions of various collector components. However, there seems to be some inter-connecting dependency issues in upgrading one by one.

I tried doing them all in a single branch, but still hit issues. This needs some more investigation.

Issues:
- #118 
- #119 
- #120 
- #121

Branch:
- https://github.com/honeycombio/opentelemetry-collector-configs/tree/mike/bump-otel-deps

**Comment by TylerHelmuth** [comment]
Since we removed the timestamp processor we don't need to update these dependencies anymore
